### ISSUE TITLE
add stats_categorical

### ISSUE THREAD

**Issue by WlanNergady** [fynn-oldenburg/GitHub-Projekt-Wissenschaftliches-Arbeiten#38]

**Comment by danfleon** [comment]
@WlanNergady, meiner Meinung nach, könntest du berechnen:

- Häufigkeiten 
- Prozentsatzes
- Streuungsmaße (Entropie)
- Modus
- Anzahl der fehlenden Werte (Falls es gibt)

**Comment by WlanNergady** [comment]
Ich habe die Anzahl der fehlenden Werte und die Entropie ergänzt... den Prozentsatz finde ich in unserem Fall nicht so spannend, da wir genau 100 Datensätze haben, insofern ist das identisch zur Häufigkeitstabelle
