### ISSUE TITLE
add stats_bivariate_metric_dichotom

### ISSUE THREAD

**Issue by WlanNergady** [fynn-oldenburg/GitHub-Projekt-Wissenschaftliches-Arbeiten#50]
Schlagt gerne Statistiken vor, die in dieser Funktion berechnet bzw. ausgegeben werden können

**Comment by danfleon** [comment]
@WlanNergady, hat du es gefragt? Wenn ja:

- Mittelwertsvergleich
- Kreuztabellen
- Boxplots
- t-Tests
- Effektstärkenmaße

Da könntest du die Gruppierung nach dichotomer Variable machen. Dann 
die Berechnung der Mittelwerte, der Standardabweichungen, des t-Tests, etc.
Zum Schluss die Ausgabe der Ergebnisse.

**Comment by fynn-oldenburg** [comment]
https://de.wikipedia.org/wiki/Zusammenhangsmaß#Für_zwei_Variablen_unterschiedlichen_Skalenniveaus
