### ISSUE TITLE
update simulation documentation

### ISSUE THREAD

**Issue by jonasmolsbeck** [fynn-oldenburg/GitHub-Projekt-Wissenschaftliches-Arbeiten#54]

**Comment by danfleon** [comment]
Meiner Meinung nach hast du die Dokumentation sehr gut gemacht. Ich werde da nichts mehr addieren.

**Comment by jonasmolsbeck** [comment]
@danfleon Alles klar. Habe einen pull request gemacht, den du noch bestätigen musst.
