### ISSUE TITLE
ERROR analysis.R >>>  bivariate_stats_categorical(data, data$Studienfach, data$Mathe)

### ISSUE THREAD

**Issue by fynn-oldenburg** [fynn-oldenburg/GitHub-Projekt-Wissenschaftliches-Arbeiten#69]
Error in if (!(x_var %in% names(data))) { (analyzing_functions.R#136): the condition has length > 1

beim aufrufen von analysis.R Zeile 20 bis 25

**Comment by fynn-oldenburg** [comment]
Aktuelle main version

**Comment by jonasmolsbeck** [comment]
Funktion richtig anwenden: `bivariate_stats_categorical(data, "Studienfach", "Mathe")`

**Comment by WlanNergady** [comment]
Habe ich geändert, kann das jemand mergen?
